{% set version = "2.1.0" %}

package:
  name: markupsafe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-{{ version }}.tar.gz
  sha256: 80beaf63ddfbc64a0452b841d8036ca0611e049650e20afcb882f5d3c266d65f

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
  run_constrained:
    - jinja2 >=3.0.0

test:
  imports:
    - markupsafe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.palletsprojects.com/p/markupsafe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python module that implements the jinja2.Markup string
  dev_url: https://github.com/pallets/markupsafe

extra:
  recipe-maintainers:
    - pelson
    - scopatz
    - ocefpaf
