{% set version = "2.0.0" %}

package:
  name: markupsafe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-{{ version }}.tar.gz
  sha256: 4fae0677f712ee090721d8b17f412f1cbceefbf0dc180fe91bab3232f38b4527

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - markupsafe

about:
  home: https://www.palletsprojects.com/p/markupsafe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python module that implements the jinja2.Markup string
  dev_url: https://github.com/pallets/markupsafe

extra:
  recipe-maintainers:
    - pelson
    - scopatz
    - ocefpaf
